version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: mysql-database
    restart: always
    environment:
      MYSQL_DATABASE: 'db'

      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # creating the table and loading data to the database
    #volumes:
     # - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
     # - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
  iso-demo:
    image: iso-demo:latest
    ports:
      - '8080:8080'
    depends_on:
      - db
